# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu
#
input {
    natural_scroll = true
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
  }

cursor {
    zoom_rigid = true
    no_hardware_cursors = false
  }


# Zoom
#bind = SUPER ALT, down, exec, hyprctl keyword cursor:zoom_factor 1.0
#bind = SUPER ALT, up, exec, hyprctl keyword cursor:zoom_factor 2.0

# Replace your current zoom bindings with these:
bind = SUPER ALT, up, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor -j | jq -r '.float' | awk '{print ($1 < 3.0) ? $1 + 0.5 : $1}')"
bind = SUPER ALT, down, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor -j | jq -r '.float' | awk '{print ($1 > 1.0) ? $1 - 0.5 : 1.0}')"
#bind = SUPER ALT, 0, exec, hyprctl keyword cursor:zoom_factor 1.0

bind = SUPER ALT, 3, exec, omarchy-cmd-screenshot

# Scriber
bind = SUPER, D, exec, /home/alfredo/.cargo/bin/wayscriber --active --no-resume-session

# Magnifier (toggle with Super+`)
#layerrule = no_screen_share on, match:namespace remagnify
bind = SUPER, grave, exec, /home/alfredo/.cargo/bin/remagnify -z 0.2 --exit-delay 400 --size 1200x600

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
